logging:
  level:
    org:
      springframework:
        security: DEBUG


server:
  port: 3000

  servlet:
    context-path: /


spring:
  application:
    name: analyticalsolution

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:mysql://localhost:3306/analytical_equipment_solutions
    username: Atharv
    password: atharv09
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

  web:
    resources:
      static-locations: file:///D:/AES/ProductImages/

  mail:
    host: smtp.gmail.com
    port: 587
    username: atharvmirgal09@gmail.com
    password: tttj iinq wzwh rshm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  base-url: http://localhost:3000/
  UPLOAD_DIR: D:/AES/ProductImages/
  sentTo: atharvmirgal09@gmail.com
  secret-key: TaK+HaV^uvCHEFsEVfypW#7g9^k*Z8$V
