logging:
  level:
    org:
      springframework:
        security: DEBUG


server:
  port: 3000

  servlet:
    context-path: /


spring:
  application:
    name: analyticalsolution

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:mysql://localhost:3306/analytical_equipment_solutions
    username: Atharv
    password: atharv09
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always